### ISSUE TITLE
Request to add Vale of Glamorgan council 

### ISSUE THREAD

**Issue by usrErr0r** [robbrad/UKBinCollectionData#151]
### Name of Council

Vale of Glamorgan Council

### Example Postcode

CF63 4RU

### Additional Information

The bin day calendar is more accurate than the live bin day check (the calendar gives the dates accounting for bank holidays where as the checker does not seem to account for bank holidays)

**Comment by dp247** [comment]
Do you have a link to the council's site please?

**Comment by usrErr0r** [comment]
> Do you have a link to the council's site please?

https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/Recycling-and-Waste.aspx

You can enter the post code, then the address (though I'm sure nine times out of ten that's not relevant) then it'll tell you what day / week you are on.

I find the calendar for the dates given after that is most accurate accommodating for bank holidays etc. 


E.g

https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/collections/Monday-Week-1.aspx

Recycling+food is weekly, garden waste is seasonal and black bags are bi weekly.

It would be nice to have the accurate date + the possible bins on that date so I looked online and found this GitHub. Hope you can help

In my opinion it would maybe be best to use the calendar page for scraping data (https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/collections/Monday-Week-1.aspx). That way the URL can be changed based on a one time manual lookup done by the user rather than inputting address information etc. but you know best I'm sure!

Thank you for your help.

**Comment by dp247** [comment]
This council is pain 😅.

I'd love to parse the big table, but for some reason, the formats vary depending on day of collection - some have an extra table in the table with the values in, and there's an inconsistent way of writing the dates (some use &, others use the word "and") - I'm comparing [this](https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/collections/Thursday-Week-2.aspx) to [this](https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/collections/Monday-Week-2.aspx).

What might be best is parsing the collection information page and working out the next collection from it to make it consistent - the only downside is that it would only show the next date for each bin type rather than the next few. Would that be okay @usrErr0r?

**Comment by usrErr0r** [comment]
> 

What a pain!

That could be the best way then - it would be okay for me. I may end up scraping just the page relevant to me for the sake of my own benefit anyway!

Thank you for looking into it

**Comment by dp247** [comment]
@usrErr0r Revisited it and got the following:

- Seperated recycling or co-mingled recycling status with weekly dates
- Specific dates from the calendar regardless of table formatting (actually, if the other pages are different, a few changes will be needed, but this will work on the two pages I linked above 😄)

All those dates are merged into one big list and ordered to return the data. We may need to investigate a limit because it's long.
