### ISSUE TITLE
Milton Keynes Council please!

### ISSUE THREAD

**Issue by aatur-ravani** [robbrad/UKBinCollectionData#248]
### Name of Council

Milton Keynes Council

### Example Postcode

MK10 9NQ

### Additional Information

https://www.milton-keynes.gov.uk/waste-and-recycling/collection-days

**Comment by davehamer** [comment]
This functionality doesn't seem to be working properly - looking at the code - it looks like it's trying to read the data from this page https://www.milton-keynes.gov.uk/waste-and-recycling/collection-days. 

It appears this page has been changed recently due to the New Year/Christmas collections - I presume when they have gone - if the council puts the same page back up with the estates listed as usual this will be back to normal.

If my assumption is incorrect, then I have another problem :)

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 133, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/councils/MiltonKeynesCityCouncil.py", line 21, in parse_data
    soup = BeautifulSoup(page.text, features="html.parser")
                         ^^^^^^^^^
AttributeError: 'str' object has no attribute 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/uk_bin_collection/sensor.py", line 75, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'str' object has no attribute 'text'`

**Comment by dannya** [comment]
> This functionality doesn't seem to be working properly - looking at the code - it looks like it's trying to read the data from this page https://www.milton-keynes.gov.uk/waste-and-recycling/collection-days.
> 
> It appears this page has been changed recently due to the New Year/Christmas collections - I presume when they have gone - if the council puts the same page back up with the estates listed as usual this will be back to normal.
> 
> If my assumption is incorrect, then I have another problem :)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/uk_bin_collection/sensor.py", line 133, in _async_update_data
>     data = await self.hass.async_add_executor_job(self.ukbcd.run)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
>     return self.client_code(
>            ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
>     return get_bin_data_class.template_method(address_url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
>     bin_data_dict = self.parse_data(
>                     ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/councils/MiltonKeynesCityCouncil.py", line 21, in parse_data
>     soup = BeautifulSoup(page.text, features="html.parser")
>                          ^^^^^^^^^
> AttributeError: 'str' object has no attribute 'text'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/uk_bin_collection/sensor.py", line 75, in async_setup_entry
>     await coordinator.async_config_entry_first_refresh()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
>     raise ex
> homeassistant.exceptions.ConfigEntryNotReady: 'str' object has no attribute 'text' 
> ```

This source no longer works, as the page has changed to a PDF - see https://github.com/robbrad/UKBinCollectionData/issues/702
