### ISSUE TITLE
West Lothian Council

### ISSUE THREAD

**Issue by Alllfff** [robbrad/UKBinCollectionData#362]
### Name of Council

West Lothian Council

### Example Postcode

EH525JE

### Additional Information

https://www.westlothian.gov.uk/article/31528/Bin-Collection-Calendar-Dates

**Comment by OliverCullimore** [comment]
Working address: 1 GOSCHEN PLACE BROXBURN EH52 5JE

**Comment by OliverCullimore** [comment]
Looks to be the same/similar system to #363

**Comment by Alllfff** [comment]
@OliverCullimore sorry for my lack of knowledge but what is the next step? Will there be an update to the drop down selection in the integration or do I need to set it up somehow? Thank you for your help!

**Comment by OliverCullimore** [comment]
@Alllfff When this issue is marked as closed support for this council would've been added.

My notes above are just to make us aware that some councils appear to be using the same/similar systems so once we integrate one of these in theory it should be quick to implement the same for the other councils.

Once that's all happened, if you're using Home Assistant then updating the custom component will then make your council appear in the Council drop-down options when adding the Bin Collection Data Integration.

**Comment by Alllfff** [comment]
Thank you! your help and work is very much appreciated!
