### ISSUE TITLE
Selenium based councils don't seem to work in HASS

### ISSUE THREAD

**Issue by bfayers** [robbrad/UKBinCollectionData#381]
### Home Assistant Version

2023.10.3

### Installation Method

Using HACS

### Name of Council (if relevant)

East Suffolk Council

### Issue Information

Selenium based councils never create entities.

Using the custom deps deployment addon for hass i've made sure that chromium-chromedriver alpine package is installed.

Manually going into the hass container run by HassOS and using python works fine: 

```
$ docker exec -it homeassistant bash      
homeassistant:/config# python3
Python 3.11.5 (main, Sep 28 2023, 17:11:18) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from uk_bin_collection.uk_bin_collection.collect_data import UKBinCollectionApp
>>> bins = UKBinCollectionApp()
>>> bins.set_args(["--postcode=ip119fj","--uprn=10093544720","EastSuffolkCouncil","https://my.eastsuffolk.gov.uk/service/Bin_collection_dates_finder"])
>>> bins.run()
'{\n    "bins": [\n        {\n            "type": "General waste",\n            "collectionDate": "20/10/2023"\n        },\n        {\n            "type": "Recycling",\n            "collectionDate": "27/10/2023"\n        }\n    ]\n}'
```

Try adding any selenium based council into hass and you will not get entities; non-selenium based options work fine (for testing I used North Lanarkshire)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by OliverCullimore** [comment]
List of current selenium-based councils:
- Broxtowe Borough Council
- Buckinghamshire Council (Chiltern, South Bucks, Wycombe)
- Derbyshire Dales District Council
- East Lindsey District Council
- East Suffolk Council
- Gateshead Council
- High Peak Council
- Neath Port Talbot Council
- North Norfolk District Council
- Northumberland Council
- Preston City Council
- Reigate and Banstead Borough Council
- Rushcliffe Borough Council
- Staffordshire Moorlands District Council
- Wakefield City Council
- West Lothian Council

It hasn't been confirmed that all of these are having issues within Home Assistant but it's likely.

I have been able to replicate the issue with Broxtowe Borough Council in my Home Assistant however haven't had chance to look at how we can fix yet.

**Comment by bfayers** [comment]
My initial thoughts of a way of doing this would be a Home Assistant addon that contains python+selenium bits and then either provides a REST api this addon could use, or just sends the data out over MQTT (with all the correct MQTT auto discovery stuff like here: https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery)

I've already had to make something that sends data into hass w/ MQTT+MQTT Discovery this week so It's something I can definitely have a look at making work.

**Comment by OliverCullimore** [comment]
I've not had chance to test my theory yet but at a guess the issue may be that the Chrome driver isn't installed/accessible to the custom component at runtime.

I'll try and have a look tomorrow at testing using something like [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) to auto-install the driver and see if that resolves this first before we look at creating an addon as I imagine that could cause complications with providing support for all the different ways Home Assistant can be installed.

**Comment by bfayers** [comment]
> I've not had chance to test my theory yet but at a guess the issue may be that the Chrome driver isn't installed/accessible to the custom component at runtime.

I'm pretty sure this must be correct at some level because I can `docker exec` into the hass container and it works fine just running python, just not from the component.

**Comment by OliverCullimore** [comment]
@bfayers I've submitted a PR with a potential fix but sadly unable to test this until it's included in a release as it's a change to the main Python library rather than the custom component itself

**Comment by bfayers** [comment]
Doesn't seem to work; in fact manually running python commands don't even work now...

**Comment by Alllfff** [comment]
Hi West Lothian still not working.

**Comment by OliverCullimore** [comment]
I assume we're now failing due to Chrome not being installed within the container which makes sense.

![image](https://github.com/robbrad/UKBinCollectionData/assets/17053927/b29c51d6-4e95-4b54-a193-f2de7865040c)

Therefore @bfayers it looks like a separate addon/docker container will likely be needed for using selenium to be possible.

I think it would be best to discuss and agree on a plan on how this should be implemented before we start any work?

I think as some initial requirements we should aim for it to:
- Be as simple to install and set up as possible
- Allow non-selenium councils to still work by simply installing the custom component

I believe using MQTT would require a broker to be set up which wouldn't meet the as simple as possible to install requirement so the REST API option is likely best here.

@robbrad feel free to jump in here

**Comment by OliverCullimore** [comment]
So thinking further, we could look to do the below:

- Implement a http server in the main bin collection library
- Create an addon which runs the http server in the Dockerfile
- Add a flag against councils in input.json that use Selenium
- Update the custom component to show an extra field to enter the URL of the addon/docker container when a council has the selenium flag against it in input.json and make a request to it passing the UPRN etc instead of calling the bin collection library locally

**Comment by robbrad** [comment]
I think if we are going down that route we would centralise the entire scrape in our own infrastructure store it. Then let the component hit our resources.

Only downside is there would be a cost for the infrastructure

**Comment by robbrad** [comment]
I wonder if @frenck would be open to having chromium added to https://github.com/home-assistant/docker/blob/master/Dockerfile 

```
apk add chromium
```

@bfayers - you could test this by cloneing the repo for HASS Docker - adding the line to the dockerfile and doing a docker build - this would then create an image locally for you to start the container - but obviously dont impact your existing hass install

**Comment by frenck** [comment]
We won't add things to our images that we don't use in our core ourselves.

**Comment by robbrad** [comment]
> We won't add things to our images that we don't use in our core ourselves.
> 

Makes sense - thank you for replying

**Comment by bfayers** [comment]
> I wonder if @frenck would be open to having chromium added to [home-assistant/docker@`master`/Dockerfile](https://github.com/home-assistant/docker/blob/master/Dockerfile?rgh-link-date=2023-11-01T08%3A16%3A43Z)
> 
> ```
> apk add chromium
> ```
> 
> @bfayers - you could test this by cloneing the repo for HASS Docker - adding the line to the dockerfile and doing a docker build - this would then create an image locally for you to start the container - but obviously dont impact your existing hass install

I had already installed the chromium and chromium-chromedriver apk packages with the custom deps deployment addon for hass, prior to opening this issue.

**Comment by OliverCullimore** [comment]
I think we might be best utilising selenium's remote web driver support and just require users to provide a URL to a web driver such as [standalone-chrome](https://hub.docker.com/r/selenium/standalone-chrome)

To achieve this we'd need to:

- Add a flag against councils in input.json that use Selenium
- Add an argument to the bin collection python library allowing a selenium URL to be passed and connect to this instead of using the local web driver
- Update the custom component to show an extra field to allow a selenium URL to be entered when a council has the selenium flag against it in input.json and pass it as an argument when running the bin collection python library
- Add instructions to README.md/wiki on how to use this

@robbrad happy with this plan?

**Comment by robbrad** [comment]
Yep sound good @OliverCullimore

**Comment by OliverCullimore** [comment]
Perfect, I'll work on a PR to implement that plan

**Comment by vishnurpatel** [comment]
Leeds Council Is also reporting no entities, from memory, I didn't think Leeds used selenium to get the data.
so not sure what the issue could be for that.
