### ISSUE TITLE
Council Request - North Yorkshire Council

### ISSUE THREAD

**Issue by iendicott** [robbrad/UKBinCollectionData#564]
### Name of Council

North Yorkshire Council

### Example Address/Postcode

LS25 6QJ

### Additional Information

https://www.northyorks.gov.uk/bin-calendar/Selby/results/10093091235

![Capture](https://github.com/robbrad/UKBinCollectionData/assets/73525618/bbdfb1b6-41b0-4912-bf5d-d3dd11736e44)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by FieldsingAround** [comment]
Just as added info on this request @robbrad , North Yorkshire Council newly combined about 8 other councils under a larger system since voting for combining councils and infrastructure in 2022/23 (detailed here: https://www.bbc.co.uk/news/uk-england-york-north-yorkshire-65140906  ) - so this particular request covers quite a significant area, would be great if this request could be prioritised.

**Comment by bfayers** [comment]
Sorted in the PR; works for the provided UPRN -- some more UPRNs outside the old Selby area would be nice to test with but I suspect it'll work anyway based on the way I've written it.

**Comment by iendicott** [comment]
Hi @bfayers Any chance it can be changed to **North Yorkshire** and from **NorthYorkshire** please?
Thanks for all your hard work BTW.

Regards Ivan

**Comment by iendicott** [comment]
Hi @robbrad Any chance it can be changed to North Yorkshire and from NorthYorkshire please?
Thanks for all your hard work BTW.

Regards Ivan

**Comment by FieldsingAround** [comment]
Thanks so much @robbrad 🙏 🙏

**Comment by robbrad** [comment]
Dont thank me I did nothing ;)

@FieldsingAround - how are you using it for Scarborough ? just using a Scarborough address?

@iendicott : do you think this should be seperate councils so people can find them or its fine under one?

**Comment by FieldsingAround** [comment]
Yes I'm just using a Scarborough address, was very straight forward to set up with the UPRN.

And on the other point, it makes sense to have them all under one, it will soon be very confusing if it's not under NYC as the old council sites become completely deprecated (as most already are). All the old councils have been combined into North Yorkshire - anyone within these districts will be aware of this already as NYC has been very clear with residents that they are taking over of management of those services, and the old councils have ceased to exist (or otherwise been replaced by smaller local bodies).

**Comment by iendicott** [comment]
> Dont thank me I did nothing ;)
> 
> @FieldsingAround - how are you using it for Scarborough ? just using a Scarborough address?
> 
> @iendicott : do you think this should be seperate councils so people can find them or its fine under one?

North Yorkshire should be fine, this has only happened in the last few years.
